"""html_to_pptx — extract an HTML presentation's content and rebuild it as an
IBM-branded .pptx.

This is a *content* conversion, not a screenshot. Each HTML slide is read for its
eyebrow, headline, lede and body blocks; that content is then re-typeset on the
official IBM layouts by `ibm_deck`. The source deck's own colors, gradients and
fonts are deliberately discarded — the output belongs to the IBM design system.

    python html_to_pptx.py deck.html -o deck.pptx --footer "Platform engineering"

It prints a per-slide report of the layout chosen and anything it could not map,
so nothing is dropped silently. Treat the result as a first pass: the script does
mechanical extraction, and a human (or Claude) still makes the editorial calls the
report flags. Requires: python-pptx, beautifulsoup4.
"""

import argparse
import re
import sys
from pathlib import Path

from bs4 import BeautifulSoup

sys.path.insert(0, str(Path(__file__).parent))
from ibm_deck import Deck  # noqa: E402

# Selectors tried in order to find the slides of an unknown HTML deck.
SLIDE_SELECTORS = ["section.slide", "section.slide-container", ".reveal .slides section",
                   "section", ".slide"]
# Chrome that is regenerated by the IBM template and must not become content.
CHROME = {"secttag", "pagenum", "progress", "dots", "nav", "footer", "eyebrow",
          "kbd", "lockup"}


def text(node, keep_bold=True):
    """Flatten a node to a single line, preserving **bold** for strong/b."""
    if node is None:
        return ""
    out = []
    for el in node.descendants:
        if getattr(el, "name", None) is None:
            parent = el.parent.name if el.parent else ""
            s = str(el)
            if keep_bold and parent in ("strong", "b"):
                s = f"**{s.strip()}**" if s.strip() else s
            out.append(s)
    return re.sub(r"\s+", " ", "".join(out)).strip()


def items(node, selector="li"):
    return [t for t in (text(li) for li in node.select(selector)) if t]


def _card_prose(card):
    """Caption becomes a bold lead-in, so the two lines read as one sentence."""
    cap, desc = text(card.select_one(".cap")), text(card.select_one(".desc"))
    if cap and desc:
        return f"**{cap}** — {desc}"
    return cap or desc


class Slide:
    """The neutral model between HTML and pptx."""

    def __init__(self, el, index):
        self.el = el
        self.index = index
        self.name = el.get("data-name") or ""
        self.eyebrow = text(el.select_one(".eyebrow"))
        h1, h2 = el.select_one("h1"), el.select_one("h2")
        self.headline = text(h1 or h2)
        self.is_big = h1 is not None
        self.lede = text(el.select_one(".lede") or el.select_one("p"))
        self.cards = [
            (text(c.select_one(".num")) or text(c.select_one("h3")), _card_prose(c))
            for c in el.select(".card")
        ]
        self.bullets = items(el, "ul li")
        self.columns = [items(col, "li") or [text(col.select_one("p"))]
                        for col in el.select(".row.split > *")]
        self.code = "\n".join(pre.get_text() for pre in el.select("pre")).strip()
        self.images = [img.get("src") for img in el.select("img[src]")]
        self.notes = text(el.select_one(".notes") or el.select_one("aside"))
        self.dropped = []

    def kind(self):
        if self.index == 0:
            return "cover"
        if self.code:
            return "code"
        if len(self.cards) >= 2:
            return "metrics"
        if len(self.columns) >= 2:
            return "columns"
        if self.images:
            return "image"
        if self.bullets:
            return "bullets"
        if self.is_big and not self.lede:
            return "section"
        if self.headline and not self.bullets and len(self.headline) < 90:
            return "statement"
        return "callout"


def convert(html_path, out_path, footer=None, selector=None, title=None,
            base_dir=None, report=print):
    soup = BeautifulSoup(Path(html_path).read_text(encoding="utf-8"), "html.parser")
    els = []
    for sel in ([selector] if selector else SLIDE_SELECTORS):
        els = soup.select(sel)
        if len(els) > 1:
            break
    if not els:
        raise SystemExit(f"no slides found in {html_path}; pass --selector")

    base = Path(base_dir or Path(html_path).parent)
    doc_title = title or text(soup.select_one("title")) or Path(html_path).stem
    deck = Deck(footer=footer)
    report(f"{len(els)} slide(s) in {html_path}")

    for i, el in enumerate(els):
        s = Slide(el, i)
        kind = s.kind()
        head = s.headline or s.name or doc_title
        notes = s.notes or None

        if kind == "cover":
            meta = [m for m in [s.lede] if m]
            deck.cover(head, label=s.eyebrow or None, meta=meta, notes=notes)
        elif kind == "section":
            deck.section(head, notes=notes)
        elif kind == "statement":
            deck.statement(head, notes=notes)
        elif kind == "metrics":
            if len(s.cards) > 3:
                s.dropped.append(f"{len(s.cards) - 3} extra card(s) — IBM data layouts hold 3")
            deck.metrics(s.cards[:3], title=head, notes=notes)
        elif kind == "columns":
            deck.columns(head, [c for c in s.columns if c][:4], notes=notes)
        elif kind == "bullets":
            body = ([s.lede] if s.lede else []) + s.bullets
            deck.columns(head, [body], notes=notes)
        elif kind == "code":
            deck.code(head, s.code, caption=s.eyebrow or None, notes=notes)
        elif kind == "image":
            img = base / s.images[0]
            if img.exists():
                deck.image(head, img, body=s.lede or None, notes=notes)
            else:
                s.dropped.append(f"image not found: {s.images[0]}")
                deck.callout(head, s.lede or "", notes=notes)
        else:
            deck.callout(head, s.lede or s.bullets or "", notes=notes)

        if len(s.images) > 1 and kind == "image":
            s.dropped.append(f"{len(s.images) - 1} extra image(s) on this slide")
        if s.code and kind != "code":
            s.dropped.append("code block not carried over")
        report(f"  {i + 1:>3}. {kind:<9} <- {head[:52]!r}"
               + ("".join(f"\n         ! {d}" for d in s.dropped) if s.dropped else ""))

    deck.end()
    deck.save(out_path)
    report(f"wrote {out_path} ({len(els) + 1} slides, incl. IBM end slide)")
    return out_path


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("html")
    ap.add_argument("-o", "--out", default=None, help="output .pptx (default: alongside the html)")
    ap.add_argument("--footer", default=None, help="running footer text")
    ap.add_argument("--selector", default=None, help="CSS selector for slide elements")
    ap.add_argument("--title", default=None, help="override the cover title")
    a = ap.parse_args(argv)
    out = a.out or str(Path(a.html).with_suffix(".pptx"))
    convert(a.html, out, footer=a.footer, selector=a.selector, title=a.title)


if __name__ == "__main__":
    main()
